// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Identity struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Provider    string
	ProviderUid string
	Username    string
	CreatedAt   time.Time
}

type Safe struct {
	UserID             uuid.UUID
	Kind               string
	Payload            []byte
	Rev                int64
	SchemaVersion      string
	RatingModelVersion string
	UpdatedAt          time.Time
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}
