// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saves.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSave = `-- name: GetSave :one
SELECT kind, payload, rev, schema_version, rating_model_version, updated_at
FROM saves
WHERE user_id = $1 AND kind = $2
`

type GetSaveParams struct {
	UserID uuid.UUID
	Kind   string
}

type GetSaveRow struct {
	Kind               string
	Payload            []byte
	Rev                int64
	SchemaVersion      string
	RatingModelVersion string
	UpdatedAt          time.Time
}

func (q *Queries) GetSave(ctx context.Context, arg GetSaveParams) (GetSaveRow, error) {
	row := q.db.QueryRow(ctx, getSave, arg.UserID, arg.Kind)
	var i GetSaveRow
	err := row.Scan(
		&i.Kind,
		&i.Payload,
		&i.Rev,
		&i.SchemaVersion,
		&i.RatingModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSave = `-- name: UpsertSave :one
INSERT INTO saves (user_id, kind, payload, rev, schema_version, rating_model_version, updated_at)
VALUES ($1, $2, $3, 1, $4, $5, now())
ON CONFLICT (user_id, kind) DO UPDATE
SET payload = EXCLUDED.payload,
    rev = saves.rev + 1,
    schema_version = EXCLUDED.schema_version,
    rating_model_version = EXCLUDED.rating_model_version,
    updated_at = now()
WHERE saves.rev = $6
RETURNING kind, payload, rev, schema_version, rating_model_version, updated_at
`

type UpsertSaveParams struct {
	UserID             uuid.UUID
	Kind               string
	Payload            []byte
	SchemaVersion      string
	RatingModelVersion string
	BaseRev            int64
}

type UpsertSaveRow struct {
	Kind               string
	Payload            []byte
	Rev                int64
	SchemaVersion      string
	RatingModelVersion string
	UpdatedAt          time.Time
}

// CAS по rev: вставка (rev=1) либо обновление ТОЛЬКО если текущий rev совпал с base_rev.
// Несовпадение rev → строка не обновляется и RETURNING пуст (:one → ErrNoRows = конфликт).
func (q *Queries) UpsertSave(ctx context.Context, arg UpsertSaveParams) (UpsertSaveRow, error) {
	row := q.db.QueryRow(ctx, upsertSave,
		arg.UserID,
		arg.Kind,
		arg.Payload,
		arg.SchemaVersion,
		arg.RatingModelVersion,
		arg.BaseRev,
	)
	var i UpsertSaveRow
	err := row.Scan(
		&i.Kind,
		&i.Payload,
		&i.Rev,
		&i.SchemaVersion,
		&i.RatingModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}
