import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
page.on("pageerror", (e) => console.log("PAGEERR", String(e)));
await page.goto("http://localhost:5273/");
await page.evaluate(() => localStorage.clear());
await page.goto("http://localhost:5273/");
await page.getByTestId("mode-arcade").click();
await page.getByTestId("arcade-seed").fill("qa-1");
await page.getByTestId("arcade-play").click();
await page.waitForSelector("[data-testid=arcade-clock]");
await page.keyboard.down("KeyD");
await page.waitForSelector("[data-testid=arcade-levelup]", { timeout: 60000 });
await page.keyboard.up("KeyD");
console.log("levelup at", await page.getByTestId("arcade-clock").textContent());
console.log(await page.locator(".arcade-levelup").innerText());
await page.getByTestId("arcade-offer-0").click();
await page.waitForTimeout(400);
console.log("after click overlay?", await page.getByTestId("arcade-levelup").count(), await page.getByTestId("arcade-clock").textContent());
if (await page.getByTestId("arcade-levelup").count()) console.log(await page.locator(".arcade-levelup").innerText());
await page.waitForTimeout(1000);
console.log("later overlay?", await page.getByTestId("arcade-levelup").count(), await page.getByTestId("arcade-clock").textContent());
await browser.close();
